backend:
  name: github
  repo: viktors-telle/personal-blog

media_folder: content/assets
public_folder: ../assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    path: "{{slug}}/{{slug}}"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: canonical, label: Canonical link }
      - { name: keywords, label: Keywords, widget: list }
      - { name: body, label: Body, widget: markdown }
